spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8090/realms/payment-system/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080

ignite:
  instance:
    name: ${IGNITE_INSTANCE_NAME:payment-ignite}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.apache.ignite: INFO
    com.zemnitskiy.dpps: DEBUG
